# Cloudflare Pages Configuration
name = "survivornet"
compatibility_date = "2024-03-15"

# The directory containing the build output
pages_build_output_dir = "SurvivorNet-React/dist"

[build]
# Command used to build the project
command = "npm run build --prefix SurvivorNet-React"
